service:
    stream:
        hmac:
            key: ENC[AES256_GCM,data:ors13Ez75sOb1uFtsjTB47lqpayreLwgkkEp2NWohis7plcjOVPRTrSM,iv:0EUpTnT6EwrBNj9+05DIamnkCG7JqnX8MxNqzjNm7Fk=,tag:h3aFEQWD1VlazxKjMrGklA==,type:str]
    omdb:
        apiKey: ENC[AES256_GCM,data:ld/J7k6I3rE=,iv:4Ndqmx8SdjYJFkDKEJ0sC6r2eQwPsPWyrLfAux/TWHs=,tag:/nX2Zy2i/CqvQXhbbq2a3A==,type:str]
    opensubtitles:
        apiKey: ENC[AES256_GCM,data:ie1uHjfxQboa702GPescy5Jum0SKJmCRmyPxAKSByxo=,iv:dWuSaHGfv35NXestvPfKqaNdiutVyhxGEHwEJJRrlLo=,tag:G5gW2jxRWfjZSedfTC620A==,type:str]
        username: ENC[AES256_GCM,data:BzJSctbgPTs=,iv:oD00yBvKJAe2zaDYgUXixaMz4vsQ7Djsqsm9fvWRq3o=,tag:lwOw40wlBC8bGeD0Z0V//g==,type:str]
        password: ENC[AES256_GCM,data:Oe6AU0LUdZCudC7nkoM/7PwCfHE=,iv:u+0kUJYma7KfC0ZUiZ9yOfEtMGXFrPXZnD1tUcZxI/s=,tag:Yb8SoprwX94xQ0HFAqdVPA==,type:str]
spring:
    datasource:
        password: ENC[AES256_GCM,data:eYA+Mmo=,iv:exh2NIWdZBbarGsmR6MlJpcYfL5VvpJLpY2z/r6ZPLA=,tag:zJY3aMMXgK8DcfkYyvYXjQ==,type:str]
sops:
    age:
        - recipient: age137rtm8kntflh674xdy3vfjdwgpq4ddlhpydtsxvv3zmpdep6lqxq2c0stp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzN0tOc2JOUTZ1VlV3OXdM
            TUdheU14Qlp1SWtwSUdmR2ZRWW1LK2hCa0Y4CmUrVzBQUUdlVVlxRmxrUExnMm55
            aFNqbUVHK0pQZURueVBOaXdsTU11WDQKLS0tIG5XVkE4Wkk2OU43Szg4MWlKRzRX
            TDl1VWZmdm96UWJRemlYdG1hTmtmMGcK1Qpr4lXB7uQkAsETtrmim4HGFwfGp+eC
            jUC3Z7NMPI5XRyauX0VLEXHZ1OciibTROTXQeRhfeElH6Fz32FjwXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T22:40:58Z"
    mac: ENC[AES256_GCM,data:XeoMtykncBaVHdMwNGaTQkAdl9LsHWegW5GlJdSnHWjNsQD3gyrE32gryUR5EcLXK1srMk4cNk7g8mIJI20XDm2E6JSHhJPOsDHsmI5y3aHFvoXfV6t0U8Vxx7F6Ye6+Rl6xce0Muih6t2wdUC68vZ9kMGUsj95ezvL3hA95nhk=,iv:WK6saJjxEZynd5basTyo347dedLx3RdrORTPxBO8Q98=,tag:oyeGehpsC4huT8VOPnXpFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
