# Using this together with nginx-ingress installed as described here - https://kubernetes.github.io/ingress-nginx/deploy/#generic-deployment

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: localmovies-ingress
    annotations:
        kubernetes.io/tls-acme: 'true'
        ingress.kubernetes.io/ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/enable-modsecurity: "true"
        nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
        nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
spec:
  ingressClassName: nginx
  rules:
    - host: movies.nathanrahm.com
      http:
        paths:
         - path: /
           pathType: ImplementationSpecific
           backend:
             service:
               name: localmovies
               port:
                 name: http
         - path: /actuator
           pathType: ImplementationSpecific
           backend:
             service:
               name: nowhere
               port:
                 name: http
  tls:
        - hosts:
              - movies.nathanrahm.com
          secretName: localmovies-tls
